#regsystem_init.py
import sqlite3
db = sqlite3.connect('regsystem.db')
db.execute("DROP TABLE IF EXISTS courseenrollment")
db.execute("CREATE TABLE courseenrollment (id INTEGER PRIMARY KEY, StudentID CHAR(8) NOT NULL, CourseCode CHAR(15) NOT NULL)")
db.execute("INSERT INTO courseenrollment (StudentID,CourseCode) VALUES ('12431964', 'COMPS362F')")
db.execute("INSERT INTO courseenrollment (StudentID,CourseCode) VALUES ('12441892', 'ELECS305F')")
db.execute("INSERT INTO courseenrollment (StudentID,CourseCode) VALUES ('12338688', 'ELECS425F')")
db.execute("INSERT INTO courseenrollment (StudentID,CourseCode) VALUES ('12431964', 'ELECS305F')")
db.execute("INSERT INTO courseenrollment (StudentID,CourseCode) VALUES ('12431964', 'ELECS425F')")
db.execute("INSERT INTO courseenrollment (StudentID,CourseCode) VALUES ('12338688', 'ELECS305F')")
db.execute("INSERT INTO courseenrollment (StudentID,CourseCode) VALUES ('12499325', 'COMPS380F')")
db.execute("INSERT INTO courseenrollment (StudentID,CourseCode) VALUES ('12335567', 'COMPS380F')")
db.execute("INSERT INTO courseenrollment (StudentID,CourseCode) VALUES ('12335567', 'COMPS382F')")
db.execute("DROP TABLE IF EXISTS course")
db.execute("CREATE TABLE course (id INTEGER PRIMARY KEY, CourseCode CHAR(15) NOT NULL, CourseTitle CHAR(100) NOT NULL, Credit NUMERIC NOT NULL)")
db.execute("INSERT INTO course (CourseCode,CourseTitle,Credit) VALUES ('COMPS362F', 'Concurrent and Network Programming', 5)")
db.execute("INSERT INTO course (CourseCode,CourseTitle,Credit) VALUES ('ELECS305F', 'Computer Networking', 5)")
db.execute("INSERT INTO course (CourseCode,CourseTitle,Credit) VALUES ('ELECS425F', 'Computer and Network Security', 5)")
db.execute("INSERT INTO course (CourseCode,CourseTitle,Credit) VALUES ('COMPS380F', 'Web Applications: Design and Development', 5)")
db.execute("INSERT INTO course (CourseCode,CourseTitle,Credit) VALUES ('COMPS381F', 'Server-side Technologies and Cloud Computing', 5)")
db.execute("INSERT INTO course (CourseCode,CourseTitle,Credit) VALUES ('COMPS363F', 'Distributed Systems and Parallel Computing', 5)")
db.execute("INSERT INTO course (CourseCode,CourseTitle,Credit) VALUES ('COMPS382F', 'Data Mining and Analytics', 5)")
db.execute("INSERT INTO course (CourseCode,CourseTitle,Credit) VALUES ('COMPS492F', 'Machine Learning', 5)")
db.execute("INSERT INTO course (CourseCode,CourseTitle,Credit) VALUES ('COMPS390F', 'Creative Programming for Games', 5)")
db.execute("INSERT INTO course (CourseCode,CourseTitle,Credit) VALUES ('ELECS363F', 'Advanced Computer Design', 5)")
db.commit()